STUDENT_DEALS = [
    # MUSIC STREAMING
    {
        "service": "Spotify Premium",
        "category": "Music Streaming",
        "regular_price_cad": 12.69,
        "student_price_cad": 6.39,
        "savings_per_month": 6.30,
        "savings_per_year": 75.60,
        "how_to_claim": "Verify via SheerID at spotify.com/ca-en/student/verification",
        "verification_method": "SheerID",
        "max_duration_years": 4,
        "note": "1-month free trial not available in Quebec",
        "keywords": ["spotify", "spotify premium", "spotify ab"],
    },
    {
        "service": "Apple Music",
        "category": "Music Streaming",
        "regular_price_cad": 11.99,
        "student_price_cad": 5.99,
        "savings_per_month": 6.00,
        "savings_per_year": 72.00,
        "how_to_claim": "Sign up via UNiDAYS at apple.com/ca/shop/buy-services/apple-music",
        "verification_method": "UNiDAYS",
        "max_duration_years": 4,
        "note": "Includes free Apple TV+ bundle",
        "keywords": ["apple music", "itunes music", "itunes"],
    },
    # VIDEO STREAMING
    {
        "service": "YouTube Premium",
        "category": "Video Streaming",
        "regular_price_cad": 13.99,
        "student_price_cad": 7.99,
        "savings_per_month": 6.00,
        "savings_per_year": 72.00,
        "how_to_claim": "Verify via SheerID at youtube.com/premium/student",
        "verification_method": "SheerID",
        "max_duration_years": 4,
        "note": "Includes YouTube Music Premium",
        "keywords": ["youtube", "youtube premium", "yt premium"],
    },
    {
        "service": "Paramount+",
        "category": "Video Streaming",
        "regular_price_cad": 9.99,
        "student_price_cad": 4.99,
        "savings_per_month": 5.00,
        "savings_per_year": 60.00,
        "how_to_claim": "Verify via SheerID at paramountplus.com",
        "verification_method": "SheerID",
        "max_duration_years": 4,
        "note": "50% off — check site for latest promo",
        "keywords": ["paramount", "paramount plus", "paramount+"],
    },
    {
        "service": "MUBI",
        "category": "Video Streaming",
        "regular_price_cad": 14.99,
        "student_price_cad": 5.99,
        "savings_per_month": 9.00,
        "savings_per_year": 108.00,
        "how_to_claim": "Verify student status at mubi.com/student",
        "verification_method": "Student email",
        "max_duration_years": None,
        "note": "Curated arthouse and indie film platform",
        "keywords": ["mubi"],
    },
    # SHOPPING & LOGISTICS
    {
        "service": "Amazon Prime",
        "category": "Shopping & Streaming",
        "regular_price_cad": 9.99,
        "student_price_cad": 4.99,
        "savings_per_month": 5.00,
        "savings_per_year": 60.00,
        "how_to_claim": "6-month free trial then 50% off at amazon.ca/prime/student — verify with .edu email",
        "verification_method": "Student email",
        "max_duration_years": 4,
        "note": "Includes Prime Video, Prime Music, free shipping",
        "keywords": ["amazon", "amazon prime", "prime video", "amazon.ca"],
    },
    # PRODUCTIVITY & OFFICE
    {
        "service": "Microsoft 365",
        "category": "Productivity",
        "regular_price_cad": 10.99,
        "student_price_cad": 0.00,
        "savings_per_month": 10.99,
        "savings_per_year": 131.88,
        "how_to_claim": "Free via Microsoft Education at microsoft.com/en-ca/education — use school email",
        "verification_method": "School email (.edu or institutional)",
        "max_duration_years": None,
        "note": "Completely FREE — Word, Excel, PowerPoint, Teams, 1TB OneDrive",
        "keywords": ["microsoft", "office 365", "microsoft 365", "word", "excel", "outlook", "onedrive", "teams"],
    },
    {
        "service": "Notion Plus",
        "category": "Productivity",
        "regular_price_cad": 12.00,
        "student_price_cad": 0.00,
        "savings_per_month": 12.00,
        "savings_per_year": 144.00,
        "how_to_claim": "Apply with school email at notion.so/product/notion-for-education",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": "FREE Plus Plan upgrade for students and educators",
        "keywords": ["notion", "notion plus", "notion ai"],
    },
    {
        "service": "Evernote Personal",
        "category": "Productivity",
        "regular_price_cad": 13.99,
        "student_price_cad": 8.39,
        "savings_per_month": 5.60,
        "savings_per_year": 67.20,
        "how_to_claim": "40% off via student verification at evernote.com",
        "verification_method": "Student email",
        "max_duration_years": None,
        "note": None,
        "keywords": ["evernote"],
    },
    {
        "service": "Todoist Pro",
        "category": "Productivity",
        "regular_price_cad": 5.99,
        "student_price_cad": 3.00,
        "savings_per_month": 2.99,
        "savings_per_year": 35.88,
        "how_to_claim": "Discounted via student/educator program at todoist.com/education",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": None,
        "keywords": ["todoist", "doist"],
    },
    {
        "service": "Grammarly Premium",
        "category": "Writing & AI",
        "regular_price_cad": 16.00,
        "student_price_cad": 6.67,
        "savings_per_month": 9.33,
        "savings_per_year": 112.00,
        "how_to_claim": "Check if your school has Grammarly for Education at grammarly.com/edu — free if enrolled. Otherwise 20% off via Student Beans",
        "verification_method": "School email or Student Beans",
        "max_duration_years": None,
        "note": "Check school portal first — may be free",
        "keywords": ["grammarly", "grammarly premium", "grammarly pro"],
    },
    {
        "service": "QuillBot Premium",
        "category": "Writing & AI",
        "regular_price_cad": 12.49,
        "student_price_cad": 9.37,
        "savings_per_month": 3.12,
        "savings_per_year": 37.44,
        "how_to_claim": "25% off annual plan via quillbot.com/student-discount",
        "verification_method": "Student verification portal",
        "max_duration_years": None,
        "note": "Built for paraphrasing, summarizing, plagiarism check",
        "keywords": ["quillbot", "quill bot"],
    },
    # DESIGN & CREATIVE
    {
        "service": "Adobe Creative Cloud",
        "category": "Design & Creative",
        "regular_price_cad": 89.99,
        "student_price_cad": 34.99,
        "savings_per_month": 55.00,
        "savings_per_year": 660.00,
        "how_to_claim": "Purchase at adobe.com/creativecloud/buy/students — verify with student email or SheerID",
        "verification_method": "SheerID or student email",
        "max_duration_years": 4,
        "note": "60%+ off — includes Photoshop, Illustrator, Premiere, After Effects",
        "keywords": ["adobe", "creative cloud", "photoshop", "illustrator", "premiere", "after effects", "lightroom", "acrobat", "adobe systems"],
    },
    {
        "service": "Canva Pro",
        "category": "Design & Creative",
        "regular_price_cad": 19.99,
        "student_price_cad": 0.00,
        "savings_per_month": 19.99,
        "savings_per_year": 239.88,
        "how_to_claim": "Apply at canva.com/education with school email — completely FREE",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": "FREE for verified students and educators",
        "keywords": ["canva", "canva pro"],
    },
    {
        "service": "Sketch",
        "category": "Design & Creative",
        "regular_price_cad": 12.00,
        "student_price_cad": 6.00,
        "savings_per_month": 6.00,
        "savings_per_year": 72.00,
        "how_to_claim": "50% off via sketch.com/store/edu — verify with school email",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": "UI/UX design tool",
        "keywords": ["sketch", "sketch app"],
    },
    # VPN & SECURITY
    {
        "service": "NordVPN",
        "category": "VPN & Security",
        "regular_price_cad": 15.99,
        "student_price_cad": 4.39,
        "savings_per_month": 11.60,
        "savings_per_year": 139.20,
        "how_to_claim": "Up to 72% off via Student Beans at nordvpn.com",
        "verification_method": "Student Beans",
        "max_duration_years": None,
        "note": "Best deal on 2-year plan",
        "keywords": ["nordvpn", "nord vpn", "nord"],
    },
    {
        "service": "Surfshark",
        "category": "VPN & Security",
        "regular_price_cad": 15.45,
        "student_price_cad": 3.19,
        "savings_per_month": 12.26,
        "savings_per_year": 147.12,
        "how_to_claim": "20% off via Student Beans at surfshark.com",
        "verification_method": "Student Beans",
        "max_duration_years": None,
        "note": "Unlimited devices",
        "keywords": ["surfshark", "surf shark"],
    },
    {
        "service": "ProtonVPN Plus",
        "category": "VPN & Security",
        "regular_price_cad": 13.99,
        "student_price_cad": 9.99,
        "savings_per_month": 4.00,
        "savings_per_year": 48.00,
        "how_to_claim": "Verify via Student Beans at proton.me/student",
        "verification_method": "Student Beans",
        "max_duration_years": None,
        "note": "Also includes ProtonMail, Proton Drive",
        "keywords": ["proton", "protonvpn", "proton vpn", "protonmail", "proton mail", "proton drive"],
    },
    {
        "service": "1Password",
        "category": "VPN & Security",
        "regular_price_cad": 5.99,
        "student_price_cad": 4.49,
        "savings_per_month": 1.50,
        "savings_per_year": 18.00,
        "how_to_claim": "25% off first year via UNiDAYS at 1password.com",
        "verification_method": "UNiDAYS",
        "max_duration_years": None,
        "note": None,
        "keywords": ["1password", "one password", "password manager"],
    },
    # CLOUD STORAGE
    {
        "service": "Dropbox Plus",
        "category": "Cloud Storage",
        "regular_price_cad": 16.58,
        "student_price_cad": 9.99,
        "savings_per_month": 6.59,
        "savings_per_year": 79.08,
        "how_to_claim": "Verify via SheerID at dropbox.com/student — 40% off",
        "verification_method": "SheerID",
        "max_duration_years": None,
        "note": None,
        "keywords": ["dropbox", "dropbox plus"],
    },
    # LEARNING & COURSES
    {
        "service": "Coursera Plus",
        "category": "Online Learning",
        "regular_price_cad": 59.00,
        "student_price_cad": 35.40,
        "savings_per_month": 23.60,
        "savings_per_year": 283.20,
        "how_to_claim": "40% off first 3 months via UNiDAYS at coursera.org",
        "verification_method": "UNiDAYS",
        "max_duration_years": None,
        "note": None,
        "keywords": ["coursera", "coursera plus"],
    },
    {
        "service": "DataCamp",
        "category": "Online Learning",
        "regular_price_cad": 45.00,
        "student_price_cad": 20.00,
        "savings_per_month": 25.00,
        "savings_per_year": 300.00,
        "how_to_claim": "50%+ off via UNiDAYS or SheerID at datacamp.com/student",
        "verification_method": "UNiDAYS or SheerID",
        "max_duration_years": None,
        "note": "Data science and ML courses",
        "keywords": ["datacamp", "data camp"],
    },
    {
        "service": "MasterClass",
        "category": "Online Learning",
        "regular_price_cad": 20.00,
        "student_price_cad": 17.00,
        "savings_per_month": 3.00,
        "savings_per_year": 36.00,
        "how_to_claim": "15% off via Student Beans at masterclass.com",
        "verification_method": "Student Beans",
        "max_duration_years": None,
        "note": None,
        "keywords": ["masterclass", "master class"],
    },
    # DEVELOPER TOOLS
    {
        "service": "GitHub Pro",
        "category": "Developer Tools",
        "regular_price_cad": 5.00,
        "student_price_cad": 0.00,
        "savings_per_month": 5.00,
        "savings_per_year": 60.00,
        "how_to_claim": "FREE via GitHub Student Developer Pack at education.github.com — includes Copilot, private repos, domain, and 100+ tools",
        "verification_method": "GitHub Student Developer Pack",
        "max_duration_years": None,
        "note": "One of the best student deals in tech — also unlocks JetBrains, Heroku credits, and more",
        "keywords": ["github", "github pro", "github copilot", "copilot"],
    },
    {
        "service": "JetBrains All Products",
        "category": "Developer Tools",
        "regular_price_cad": 32.00,
        "student_price_cad": 0.00,
        "savings_per_month": 32.00,
        "savings_per_year": 384.00,
        "how_to_claim": "FREE via GitHub Student Pack or directly at jetbrains.com/student — includes IntelliJ, PyCharm, WebStorm, DataGrip",
        "verification_method": "School email or GitHub Student Pack",
        "max_duration_years": None,
        "note": "All JetBrains IDEs free — renew annually while enrolled",
        "keywords": ["jetbrains", "intellij", "pycharm", "webstorm", "datagrip", "rider", "clion"],
    },
    # WELLNESS & FITNESS
    {
        "service": "Headspace",
        "category": "Wellness",
        "regular_price_cad": 17.99,
        "student_price_cad": 1.60,
        "savings_per_month": 16.39,
        "savings_per_year": 196.68,
        "how_to_claim": "85% off ($9.99/year) via SheerID at headspace.com/student",
        "verification_method": "SheerID",
        "max_duration_years": None,
        "note": "One of the steepest student discounts available — $9.99/year total",
        "keywords": ["headspace", "head space", "meditation"],
    },
    # WEBSITE BUILDERS
    {
        "service": "Wix Premium",
        "category": "Website Builder",
        "regular_price_cad": 22.00,
        "student_price_cad": 11.00,
        "savings_per_month": 11.00,
        "savings_per_year": 132.00,
        "how_to_claim": "50% off annual plans via Student Beans at wix.com",
        "verification_method": "Student Beans",
        "max_duration_years": None,
        "note": None,
        "keywords": ["wix", "wix premium"],
    },
    # PROJECT MANAGEMENT
    {
        "service": "Monday.com",
        "category": "Project Management",
        "regular_price_cad": 12.00,
        "student_price_cad": 0.00,
        "savings_per_month": 12.00,
        "savings_per_year": 144.00,
        "how_to_claim": "Free via Monday.com Student Program at monday.com/lp/education",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": "Free for student classes and organizations",
        "keywords": ["monday.com", "monday", "monday.com subscription"],
    },
    {
        "service": "Miro",
        "category": "Project Management",
        "regular_price_cad": 12.00,
        "student_price_cad": 0.00,
        "savings_per_month": 12.00,
        "savings_per_year": 144.00,
        "how_to_claim": "Free Education plan at miro.com/education — unlimited boards",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": "Unlimited boards free for students",
        "keywords": ["miro", "miro board"],
    },
    # TELECOM
    {
        "service": "Rogers Student Plan",
        "category": "Mobile",
        "regular_price_cad": 75.00,
        "student_price_cad": 50.00,
        "savings_per_month": 25.00,
        "savings_per_year": 300.00,
        "how_to_claim": "Ask in-store or at rogers.com/student — requires student ID",
        "verification_method": "Student ID",
        "max_duration_years": None,
        "note": "25GB data plan — pricing varies by season",
        "keywords": ["rogers", "rogers wireless", "rogers mobile", "rogers plan"],
    },
    {
        "service": "TELUS Student Plan",
        "category": "Mobile",
        "regular_price_cad": 75.00,
        "student_price_cad": 60.00,
        "savings_per_month": 15.00,
        "savings_per_year": 180.00,
        "how_to_claim": "Available at telus.com — 15% off + 3GB extra data",
        "verification_method": "Student ID",
        "max_duration_years": None,
        "note": None,
        "keywords": ["telus", "telus mobile", "telus wireless"],
    },
    # AI TOOLS
    {
        "service": "Google Gemini Advanced",
        "category": "AI Tools",
        "regular_price_cad": 29.99,
        "student_price_cad": 0.00,
        "savings_per_month": 29.99,
        "savings_per_year": 359.88,
        "how_to_claim": "Enroll in Google AI Pro for free via one.google.com/about/ai-premium/student — includes Gemini 1.5 Pro, NotebookLM Plus, and 2 TB storage",
        "verification_method": "School email (.edu or institutional)",
        "max_duration_years": 1,
        "note": "12 months FREE — one of the best AI student offers available",
        "keywords": ["google", "gemini", "google gemini", "google one", "notebooklm", "google ai"],
    },
    {
        "service": "Cursor Pro",
        "category": "AI Tools",
        "regular_price_cad": 27.00,
        "student_price_cad": 0.00,
        "savings_per_month": 27.00,
        "savings_per_year": 324.00,
        "how_to_claim": "Apply at cursor.com/students with your school email — 1 year free for verified students",
        "verification_method": "School email",
        "max_duration_years": 1,
        "note": "FREE for 1 year — AI-powered code editor, normally ~$20 USD/month",
        "keywords": ["cursor", "cursor pro", "cursor ai", "cursor editor"],
    },
    {
        "service": "Perplexity Pro",
        "category": "AI Tools",
        "regular_price_cad": 27.00,
        "student_price_cad": 13.50,
        "savings_per_month": 13.50,
        "savings_per_year": 162.00,
        "how_to_claim": "50% off via student portal at perplexity.ai/student — verify with school email",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": "AI-powered research assistant — 50% off Pro plan",
        "keywords": ["perplexity", "perplexity ai", "perplexity pro"],
    },
    {
        "service": "Julius AI",
        "category": "AI Tools",
        "regular_price_cad": 27.00,
        "student_price_cad": 8.10,
        "savings_per_month": 18.90,
        "savings_per_year": 226.80,
        "how_to_claim": "70% student discount at julius.ai — verify with school email or student ID",
        "verification_method": "School email or student ID",
        "max_duration_years": None,
        "note": "Advanced data analysis and visualization AI — 70% off",
        "keywords": ["julius", "julius ai"],
    },
    {
        "service": "HyperWrite",
        "category": "AI Tools",
        "regular_price_cad": 27.00,
        "student_price_cad": 13.50,
        "savings_per_month": 13.50,
        "savings_per_year": 162.00,
        "how_to_claim": "50% student discount at hyperwriteai.com/student — verify with school email",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": "AI writing assistant — 50% off Pro plan",
        "keywords": ["hyperwrite", "hyper write", "hyperwrite ai"],
    },
    {
        "service": "Otter.ai Pro",
        "category": "AI Tools",
        "regular_price_cad": 23.00,
        "student_price_cad": 18.40,
        "savings_per_month": 4.60,
        "savings_per_year": 55.20,
        "how_to_claim": "20% off Pro plan at otter.ai — sign up with school email for automatic discount",
        "verification_method": "School email",
        "max_duration_years": None,
        "note": "AI meeting transcription and note-taking — 20% off Pro",
        "keywords": ["otter", "otter.ai", "otter ai"],
    },
]
