export interface StudentDiscountCatalogEntry {
  serviceId: string;
  serviceName: string;
  aliases: string[];
  regularPriceMonthly: number;
  studentPriceMonthly: number;
  currency: string;
  region: string;
  verificationMethod: string;
  offerUrl: string;
  lastChecked: string;
  isActive: boolean;
  howToClaim?: string;
  note?: string;
  category?: string;
}

// Seed catalog for MVP development. Keep separate from production-managed offer data.
export const STUDENT_DISCOUNT_CATALOG_SEED: StudentDiscountCatalogEntry[] = [
  {
    serviceId: "spotify-us",
    serviceName: "Spotify Premium",
    aliases: ["spotify", "spotify usa"],
    regularPriceMonthly: 11.99,
    studentPriceMonthly: 5.99,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://www.spotify.com/us/student/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "apple-music-us",
    serviceName: "Apple Music",
    aliases: ["apple music", "apple com bill", "apple bill", "apple services"],
    regularPriceMonthly: 10.99,
    studentPriceMonthly: 5.99,
    currency: "USD",
    region: "US",
    verificationMethod: "UNiDAYS",
    offerUrl: "https://www.apple.com/apple-music/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "youtube-premium-us",
    serviceName: "YouTube Premium",
    aliases: ["youtube premium", "google youtube", "google youtube premium", "youtube"],
    regularPriceMonthly: 13.99,
    studentPriceMonthly: 7.99,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://www.youtube.com/premium/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "notion-us",
    serviceName: "Notion Plus",
    aliases: ["notion", "notion labs"],
    regularPriceMonthly: 10,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "Student email",
    offerUrl: "https://www.notion.com/product/notion-for-education",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "canva-us",
    serviceName: "Canva Pro",
    aliases: ["canva", "canva pty", "canva com"],
    regularPriceMonthly: 14.99,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "Education verification",
    offerUrl: "https://www.canva.com/education/students/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "adobe-us",
    serviceName: "Adobe Creative Cloud",
    aliases: ["adobe", "adobe inc", "adobe creative cloud"],
    regularPriceMonthly: 59.99,
    studentPriceMonthly: 19.99,
    currency: "USD",
    region: "US",
    verificationMethod: "Student verification",
    offerUrl: "https://www.adobe.com/creativecloud/buy/students.html",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "amazon-prime-student-us",
    serviceName: "Amazon Prime",
    aliases: ["amazon prime", "amzn prime", "prime video", "amazon digital"],
    regularPriceMonthly: 14.99,
    studentPriceMonthly: 7.49,
    currency: "USD",
    region: "US",
    verificationMethod: "Student email",
    offerUrl: "https://www.amazon.com/prime/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "hulu-us",
    serviceName: "Hulu",
    aliases: ["hulu", "hulu with ads"],
    regularPriceMonthly: 11.99,
    studentPriceMonthly: 1.99,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://www.hulu.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "max-us",
    serviceName: "Max",
    aliases: ["max", "hbo max", "max basic with ads"],
    regularPriceMonthly: 9.99,
    studentPriceMonthly: 4.99,
    currency: "USD",
    region: "US",
    verificationMethod: "UNiDAYS",
    offerUrl: "https://help.max.com/US/Answer/Detail/000002583",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "github-copilot-us",
    serviceName: "GitHub Copilot Pro",
    aliases: ["github copilot", "copilot", "github", "github inc"],
    regularPriceMonthly: 10,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "GitHub Education verification",
    offerUrl: "https://github.com/features/copilot/plans",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "microsoft-365-us",
    serviceName: "Microsoft 365 Personal",
    aliases: ["microsoft 365", "office 365", "office 365 personal", "microsoft", "msft"],
    regularPriceMonthly: 9.99,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "Eligible school email",
    offerUrl: "https://www.microsoft.com/en-us/education/products/office",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "spotify-ca",
    serviceName: "Spotify Premium",
    aliases: ["spotify", "spotify usa"],
    regularPriceMonthly: 11.99,
    studentPriceMonthly: 5.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "SheerID",
    offerUrl: "https://www.spotify.com/ca-en/student/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "apple-music-ca",
    serviceName: "Apple Music",
    aliases: ["apple music", "apple com bill", "apple bill", "apple services"],
    regularPriceMonthly: 10.99,
    studentPriceMonthly: 5.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "UNiDAYS",
    offerUrl: "https://www.apple.com/ca/apple-music/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "youtube-premium-ca",
    serviceName: "YouTube Premium",
    aliases: ["youtube premium", "google youtube", "google youtube premium", "youtube"],
    regularPriceMonthly: 12.99,
    studentPriceMonthly: 7.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "SheerID",
    offerUrl: "https://www.youtube.com/premium/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "notion-ca",
    serviceName: "Notion Plus",
    aliases: ["notion", "notion labs"],
    regularPriceMonthly: 10,
    studentPriceMonthly: 0,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student email",
    offerUrl: "https://www.notion.com/product/notion-for-education",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "canva-ca",
    serviceName: "Canva Pro",
    aliases: ["canva", "canva pty", "canva com"],
    regularPriceMonthly: 16.99,
    studentPriceMonthly: 0,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Education verification",
    offerUrl: "https://www.canva.com/education/students/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "adobe-ca",
    serviceName: "Adobe Creative Cloud",
    aliases: ["adobe", "adobe inc", "adobe creative cloud"],
    regularPriceMonthly: 69.99,
    studentPriceMonthly: 25.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student verification",
    offerUrl: "https://www.adobe.com/ca/creativecloud/buy/students.html",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "amazon-prime-student-ca",
    serviceName: "Amazon Prime",
    aliases: ["amazon prime", "amzn prime", "prime video", "amazon digital"],
    regularPriceMonthly: 9.99,
    studentPriceMonthly: 4.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student email",
    offerUrl: "https://www.amazon.ca/prime/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "github-copilot-ca",
    serviceName: "GitHub Copilot Pro",
    aliases: ["github copilot", "copilot", "github", "github inc"],
    regularPriceMonthly: 10,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "CA",
    verificationMethod: "GitHub Education verification",
    offerUrl: "https://github.com/features/copilot/plans",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Developer Tools",
    howToClaim: "FREE via GitHub Student Developer Pack at education.github.com — includes Copilot, private repos, domain, and 100+ tools",
    note: "Also unlocks JetBrains, Heroku credits, and more",
  },

  // ── VIDEO STREAMING ──────────────────────────────────────────
  {
    serviceId: "paramount-plus-us",
    serviceName: "Paramount+",
    aliases: ["paramount", "paramount plus", "paramount+", "cbs all access"],
    regularPriceMonthly: 7.99,
    studentPriceMonthly: 3.99,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://www.paramountplus.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Video Streaming",
    howToClaim: "Verify via SheerID at paramountplus.com — 50% off",
  },
  {
    serviceId: "paramount-plus-ca",
    serviceName: "Paramount+",
    aliases: ["paramount", "paramount plus", "paramount+"],
    regularPriceMonthly: 9.99,
    studentPriceMonthly: 4.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "SheerID",
    offerUrl: "https://www.paramountplus.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Video Streaming",
    howToClaim: "Verify via SheerID at paramountplus.com",
  },
  {
    serviceId: "mubi-us",
    serviceName: "MUBI",
    aliases: ["mubi"],
    regularPriceMonthly: 12.99,
    studentPriceMonthly: 5.99,
    currency: "USD",
    region: "US",
    verificationMethod: "Student email",
    offerUrl: "https://mubi.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Video Streaming",
    howToClaim: "Verify student status at mubi.com/student",
    note: "Curated arthouse and indie film platform",
  },
  {
    serviceId: "hulu-ca",
    serviceName: "Hulu",
    aliases: ["hulu", "hulu with ads"],
    regularPriceMonthly: 7.99,
    studentPriceMonthly: 1.99,
    currency: "USD",
    region: "CA",
    verificationMethod: "SheerID",
    offerUrl: "https://www.hulu.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Video Streaming",
    howToClaim: "Verify via SheerID at hulu.com/student",
  },

  // ── VPN & SECURITY ───────────────────────────────────────────
  {
    serviceId: "nordvpn-us",
    serviceName: "NordVPN",
    aliases: ["nordvpn", "nord vpn", "nord", "nord security"],
    regularPriceMonthly: 13.99,
    studentPriceMonthly: 4.39,
    currency: "USD",
    region: "US",
    verificationMethod: "Student Beans",
    offerUrl: "https://nordvpn.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "VPN & Security",
    howToClaim: "Up to 72% off via Student Beans at nordvpn.com",
    note: "Best deal on 2-year plan",
  },
  {
    serviceId: "nordvpn-ca",
    serviceName: "NordVPN",
    aliases: ["nordvpn", "nord vpn", "nord", "nord security"],
    regularPriceMonthly: 15.99,
    studentPriceMonthly: 4.39,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student Beans",
    offerUrl: "https://nordvpn.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "VPN & Security",
    howToClaim: "Up to 72% off via Student Beans at nordvpn.com",
    note: "Best deal on 2-year plan",
  },
  {
    serviceId: "surfshark-us",
    serviceName: "Surfshark",
    aliases: ["surfshark", "surf shark"],
    regularPriceMonthly: 12.95,
    studentPriceMonthly: 3.19,
    currency: "USD",
    region: "US",
    verificationMethod: "Student Beans",
    offerUrl: "https://surfshark.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "VPN & Security",
    howToClaim: "20% off via Student Beans at surfshark.com",
    note: "Unlimited devices",
  },
  {
    serviceId: "protonvpn-us",
    serviceName: "ProtonVPN Plus",
    aliases: ["proton", "protonvpn", "proton vpn", "protonmail", "proton mail", "proton drive"],
    regularPriceMonthly: 9.99,
    studentPriceMonthly: 6.99,
    currency: "USD",
    region: "US",
    verificationMethod: "Student Beans",
    offerUrl: "https://proton.me/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "VPN & Security",
    howToClaim: "Verify via Student Beans at proton.me/student",
    note: "Also includes ProtonMail, Proton Drive",
  },
  {
    serviceId: "1password-us",
    serviceName: "1Password",
    aliases: ["1password", "one password", "agilebits"],
    regularPriceMonthly: 4.99,
    studentPriceMonthly: 3.74,
    currency: "USD",
    region: "US",
    verificationMethod: "UNiDAYS",
    offerUrl: "https://1password.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "VPN & Security",
    howToClaim: "25% off first year via UNiDAYS at 1password.com",
  },

  // ── CLOUD STORAGE ────────────────────────────────────────────
  {
    serviceId: "dropbox-us",
    serviceName: "Dropbox Plus",
    aliases: ["dropbox", "dropbox plus", "dropbox inc"],
    regularPriceMonthly: 11.99,
    studentPriceMonthly: 7.19,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://dropbox.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Cloud Storage",
    howToClaim: "Verify via SheerID at dropbox.com/student — 40% off",
  },

  // ── PRODUCTIVITY & WRITING ───────────────────────────────────
  {
    serviceId: "todoist-us",
    serviceName: "Todoist Pro",
    aliases: ["todoist", "doist"],
    regularPriceMonthly: 4.99,
    studentPriceMonthly: 2.50,
    currency: "USD",
    region: "US",
    verificationMethod: "School email",
    offerUrl: "https://todoist.com/education",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Productivity",
    howToClaim: "Discounted via student/educator program at todoist.com/education",
  },
  {
    serviceId: "evernote-us",
    serviceName: "Evernote Personal",
    aliases: ["evernote"],
    regularPriceMonthly: 10.99,
    studentPriceMonthly: 6.59,
    currency: "USD",
    region: "US",
    verificationMethod: "Student email",
    offerUrl: "https://evernote.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Productivity",
    howToClaim: "40% off via student verification at evernote.com",
  },
  {
    serviceId: "grammarly-us",
    serviceName: "Grammarly Premium",
    aliases: ["grammarly", "grammarly premium", "grammarly pro"],
    regularPriceMonthly: 12.00,
    studentPriceMonthly: 6.67,
    currency: "USD",
    region: "US",
    verificationMethod: "School email or Student Beans",
    offerUrl: "https://grammarly.com/edu",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Writing & AI",
    howToClaim: "Check if your school has Grammarly for Education at grammarly.com/edu — may be free. Otherwise 20% off via Student Beans",
    note: "Check school portal first — may be completely free",
  },
  {
    serviceId: "quillbot-us",
    serviceName: "QuillBot Premium",
    aliases: ["quillbot", "quill bot"],
    regularPriceMonthly: 9.95,
    studentPriceMonthly: 7.46,
    currency: "USD",
    region: "US",
    verificationMethod: "Student verification portal",
    offerUrl: "https://quillbot.com/student-discount",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Writing & AI",
    howToClaim: "25% off annual plan via quillbot.com/student-discount",
    note: "Built for paraphrasing, summarizing, plagiarism check",
  },

  // ── DESIGN ───────────────────────────────────────────────────
  {
    serviceId: "sketch-us",
    serviceName: "Sketch",
    aliases: ["sketch", "sketch app", "bohemian coding"],
    regularPriceMonthly: 9.00,
    studentPriceMonthly: 4.50,
    currency: "USD",
    region: "US",
    verificationMethod: "School email",
    offerUrl: "https://sketch.com/store/edu",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Design & Creative",
    howToClaim: "50% off via sketch.com/store/edu — verify with school email",
    note: "UI/UX design tool",
  },

  // ── ONLINE LEARNING ──────────────────────────────────────────
  {
    serviceId: "coursera-us",
    serviceName: "Coursera Plus",
    aliases: ["coursera", "coursera plus"],
    regularPriceMonthly: 49.00,
    studentPriceMonthly: 29.40,
    currency: "USD",
    region: "US",
    verificationMethod: "UNiDAYS",
    offerUrl: "https://coursera.org",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Online Learning",
    howToClaim: "40% off first 3 months via UNiDAYS at coursera.org",
  },
  {
    serviceId: "datacamp-us",
    serviceName: "DataCamp",
    aliases: ["datacamp", "data camp"],
    regularPriceMonthly: 33.25,
    studentPriceMonthly: 14.83,
    currency: "USD",
    region: "US",
    verificationMethod: "UNiDAYS or SheerID",
    offerUrl: "https://datacamp.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Online Learning",
    howToClaim: "50%+ off via UNiDAYS or SheerID at datacamp.com/student",
    note: "Data science and ML courses",
  },
  {
    serviceId: "masterclass-us",
    serviceName: "MasterClass",
    aliases: ["masterclass", "master class"],
    regularPriceMonthly: 15.00,
    studentPriceMonthly: 12.75,
    currency: "USD",
    region: "US",
    verificationMethod: "Student Beans",
    offerUrl: "https://masterclass.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Online Learning",
    howToClaim: "15% off via Student Beans at masterclass.com",
  },

  // ── DEVELOPER TOOLS ──────────────────────────────────────────
  {
    serviceId: "jetbrains-us",
    serviceName: "JetBrains All Products",
    aliases: ["jetbrains", "intellij", "pycharm", "webstorm", "datagrip", "rider", "clion"],
    regularPriceMonthly: 24.90,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "School email or GitHub Student Pack",
    offerUrl: "https://jetbrains.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Developer Tools",
    howToClaim: "FREE via GitHub Student Pack or directly at jetbrains.com/student — includes IntelliJ, PyCharm, WebStorm, DataGrip",
    note: "All JetBrains IDEs free — renew annually while enrolled",
  },

  // ── WELLNESS ─────────────────────────────────────────────────
  {
    serviceId: "headspace-us",
    serviceName: "Headspace",
    aliases: ["headspace", "head space", "meditation"],
    regularPriceMonthly: 12.99,
    studentPriceMonthly: 0.83,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://headspace.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Wellness",
    howToClaim: "85% off ($9.99/year) via SheerID at headspace.com/student",
    note: "One of the steepest student discounts available — $9.99/year total",
  },

  // ── WEBSITE & PROJECT MANAGEMENT ────────────────────────────
  {
    serviceId: "wix-us",
    serviceName: "Wix Premium",
    aliases: ["wix", "wix premium", "wix.com"],
    regularPriceMonthly: 17.00,
    studentPriceMonthly: 8.50,
    currency: "USD",
    region: "US",
    verificationMethod: "Student Beans",
    offerUrl: "https://wix.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Website Builder",
    howToClaim: "50% off annual plans via Student Beans at wix.com",
  },
  {
    serviceId: "monday-us",
    serviceName: "Monday.com",
    aliases: ["monday.com", "monday", "monday com"],
    regularPriceMonthly: 9.00,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "School email",
    offerUrl: "https://monday.com/lp/education",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Project Management",
    howToClaim: "Free via Monday.com Student Program at monday.com/lp/education",
    note: "Free for student classes and organizations",
  },
  {
    serviceId: "miro-us",
    serviceName: "Miro",
    aliases: ["miro", "miro board", "realtimeboard"],
    regularPriceMonthly: 8.00,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "School email",
    offerUrl: "https://miro.com/education",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Project Management",
    howToClaim: "Free Education plan at miro.com/education — unlimited boards",
    note: "Unlimited boards free for students",
  },

  // ── TELECOM (CA) ─────────────────────────────────────────────
  {
    serviceId: "rogers-ca",
    serviceName: "Rogers Student Plan",
    aliases: ["rogers", "rogers wireless", "rogers mobile", "rogers plan", "rogers canada"],
    regularPriceMonthly: 75.00,
    studentPriceMonthly: 50.00,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student ID",
    offerUrl: "https://rogers.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Mobile",
    howToClaim: "Ask in-store or at rogers.com/student — requires student ID",
    note: "25GB data plan — pricing varies by season",
  },
  {
    serviceId: "telus-ca",
    serviceName: "TELUS Student Plan",
    aliases: ["telus", "telus mobile", "telus wireless", "telus canada"],
    regularPriceMonthly: 75.00,
    studentPriceMonthly: 60.00,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student ID",
    offerUrl: "https://telus.com",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "Mobile",
    howToClaim: "Available at telus.com — 15% off + 3GB extra data",
  },

  // ── AI TOOLS ─────────────────────────────────────────────────
  {
    serviceId: "gemini-advanced-us",
    serviceName: "Google Gemini Advanced",
    aliases: ["google", "gemini", "google gemini", "google one", "notebooklm", "google ai", "google ai pro"],
    regularPriceMonthly: 21.99,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "School email (.edu or institutional)",
    offerUrl: "https://one.google.com/about/ai-premium/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "AI Tools",
    howToClaim: "Enroll in Google AI Pro for free via one.google.com/about/ai-premium/student — includes Gemini 1.5 Pro, NotebookLM Plus, and 2 TB storage",
    note: "12 months FREE — one of the best AI student offers available",
  },
  {
    serviceId: "gemini-advanced-ca",
    serviceName: "Google Gemini Advanced",
    aliases: ["google", "gemini", "google gemini", "google one", "notebooklm", "google ai", "google ai pro"],
    regularPriceMonthly: 29.99,
    studentPriceMonthly: 0,
    currency: "CAD",
    region: "CA",
    verificationMethod: "School email (.edu or institutional)",
    offerUrl: "https://one.google.com/about/ai-premium/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "AI Tools",
    howToClaim: "Enroll in Google AI Pro for free via one.google.com/about/ai-premium/student",
    note: "12 months FREE — includes Gemini 1.5 Pro, NotebookLM Plus, 2 TB storage",
  },
  {
    serviceId: "cursor-pro-us",
    serviceName: "Cursor Pro",
    aliases: ["cursor", "cursor pro", "cursor ai", "cursor editor"],
    regularPriceMonthly: 20.00,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "School email",
    offerUrl: "https://cursor.com/students",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "AI Tools",
    howToClaim: "Apply at cursor.com/students with your school email — 1 year free for verified students",
    note: "FREE for 1 year — AI-powered code editor",
  },
  {
    serviceId: "perplexity-pro-us",
    serviceName: "Perplexity Pro",
    aliases: ["perplexity", "perplexity ai", "perplexity pro"],
    regularPriceMonthly: 20.00,
    studentPriceMonthly: 10.00,
    currency: "USD",
    region: "US",
    verificationMethod: "School email",
    offerUrl: "https://perplexity.ai/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "AI Tools",
    howToClaim: "50% off via student portal at perplexity.ai/student — verify with school email",
    note: "AI-powered research assistant",
  },
  {
    serviceId: "julius-ai-us",
    serviceName: "Julius AI",
    aliases: ["julius", "julius ai"],
    regularPriceMonthly: 20.00,
    studentPriceMonthly: 6.00,
    currency: "USD",
    region: "US",
    verificationMethod: "School email or student ID",
    offerUrl: "https://julius.ai",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "AI Tools",
    howToClaim: "70% student discount at julius.ai — verify with school email or student ID",
    note: "Advanced data analysis and visualization AI",
  },
  {
    serviceId: "hyperwrite-us",
    serviceName: "HyperWrite",
    aliases: ["hyperwrite", "hyper write", "hyperwrite ai"],
    regularPriceMonthly: 19.99,
    studentPriceMonthly: 9.99,
    currency: "USD",
    region: "US",
    verificationMethod: "School email",
    offerUrl: "https://hyperwriteai.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "AI Tools",
    howToClaim: "50% student discount at hyperwriteai.com/student — verify with school email",
    note: "AI writing assistant — 50% off Pro plan",
  },
  {
    serviceId: "otter-ai-us",
    serviceName: "Otter.ai Pro",
    aliases: ["otter", "otter.ai", "otter ai"],
    regularPriceMonthly: 16.99,
    studentPriceMonthly: 13.59,
    currency: "USD",
    region: "US",
    verificationMethod: "School email",
    offerUrl: "https://otter.ai",
    lastChecked: "2026-03-14",
    isActive: true,
    category: "AI Tools",
    howToClaim: "20% off Pro plan at otter.ai — sign up with school email for automatic discount",
    note: "AI meeting transcription and note-taking",
  },
];
